version: '3.8'
services:
    php:
        build:
            context: "docker/php"
            dockerfile: "Dockerfile"
        restart: always
        container_name: user_crud_client_php
        volumes:
            - './project:/var/www/html'
        env_file:
            - .env
        networks:
            - user_crud

    nginx:
        image: nginx:1.21.3-alpine
        restart: always
        container_name: user_crud_client_nginx
        volumes:
            - './project:/var/www/html'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
        environment:
            - TZ
        links:
            - php
        networks:
            - user_crud
networks:
    user_crud:
        external: true
