#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\UserManageCommand;

$app = new Application();
$app->add(new UserManageCommand());
$app->run();
